# Generated by Django 4.1.7 on 2023-02-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandmodel",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="cateogrymodel",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
